# === Модель и артефакты ===
model_dir: /path/to/model_dir                  # содержит config.json, vocab.json, mel_stats.pth, dvae.pth, model.pth

# === Данные ===
data:
  metadata_csv: /path/to/metadata.csv          # sep="|", обязательно содержит audio_path|speaker_name
  text_column: text_accent                     # имя текстовой колонки в metadata.csv
  use_sampler: false                           # true — включить сэмплер по длинам текста
  sampler_char_border: 150                     # порог длины текста в символах
  sampler_upsamle_prob: 0.7                    # вероятность отбора строк короче порога

# === Тренировка ===
train:
  device: cuda                                 # cuda / cpu
  batch_size: 16
  num_workers: 4
  grad_accum_steps: 1
  total_steps: 100000
  eval_steps: 500                              # каждые N шагов — чекпоинт + валидация
  lr: 5.0e-6
  betas: [0.9, 0.96]
  weight_decay: 0.0
  eps: 1.0e-8
  grad_clip_norm: 1.0
  seed: 42

# === Сессия ===
exp:
  exp_dir: /path/to/exp_dir                    # директория для логов, чекпоинтов, CSV метрик
  resume: false                                # true — продолжить обучение с последнего чекпоинта

# === Валидация ===
eval:
  texts_json_path: /path/to/eval_texts.json    # JSON: [{"text": "...", "speaker": "..."}, ...]
  ref_wav_path: /path/to/ref_audio.wav         # эталонный голос для оценки качества

# === Neptune (опционально) ===
# neptune:
#   project: workspace/project-name            # обязательный параметр проекта в neptune.ai
#   api_token: ${NEPTUNE_API_TOKEN}            # токен можно прокинуть через конфиг или окружение
#   experiment_name: my-experiment             # имя эксперимента
#   dependencies_path: /path/to/requirements.txt
#   run_id: RUX-1                              # чтобы продолжить существующий запуск
#   tags: [tts, experiment]                    # список тегов
#   env_path: /path/to/.env                    # путь до .env для загрузки переменных
